### ISSUE TITLE
Safe is not supported in the web app when L1 contract is used for proxy creation on Polygon

### ISSUE THREAD

**Issue by alexb5dh** [safe-global/safe-deployments#112]
- I have a Gnosis Safe on Polygon chain [created](https://polygonscan.com/tx/0x51d0c7d091c295d58de65d79d4d911845789241957979f9803b0118f906e37a6#eventlog) by sending `Create Proxy` using [Safe 1.3.0](https://polygonscan.com/address/0xd9db270c1b5e3bd161e8c8503c55ceabee709552) as a base contract. Same address is used on Ethereum chain.
- Importing created Safe to https://gnosis-safe.io/app shows **"This Safe was created with an unsupported base contract. The web interface might not work correctly."**.
- If Safe is [created](https://polygonscan.com/tx/0x6377d2cb09c203e457dffa0d1ffd0d0c86d2b124f57592bb7b725e4450743fb6#eventlog) from web app, another contract is used as base - [Safe L2 1.3.0](https://polygonscan.com/address/0x3e5c63644e683549055b9be8653de26e0b4cd36e).

I'm not sure if this warning is a bug or intended behaviour. It seems the only difference in source code between regular 1.3.0 and L2 versions, is that L2 emits additional `SafeMultiSigTransaction` and `SafeModuleTransaction` events. Ignoring the warning and sending transaction via imported Safe from web app also works as expected.

If only L2 version is intended to be used as a base on Polygon, what is the reason behind having regular one on this chain?

**Comment by rmeissner** [comment]
The regular one can be used via other tools (i.e. clis or a different indexer). The indexers run by the Safe team on polygon don't rely on tracing and therefore require events.

This repo is purely about the contracts. They can be used in many ways. Providing indexing support is a different issue and is more related to the https://github.com/safe-global/safe-transaction-service
