### ISSUE TITLE
Publish the latest branch to npm

### ISSUE THREAD

**Issue by swetshaw** [safe-global/safe-deployments#121]
I see that the last publication happened 2 months back. Since then a lot of chains have been added that we need for our project. I request to please publish the latest changes to npm.

**Comment by akshatcx** [comment]
It would be helpful here too @rmeissner

**Comment by germartinez** [comment]
Hello @swetshaw @akshatcx

The new version `1.17.0` was published last week: https://www.npmjs.com/package/@gnosis.pm/safe-deployments/v/1.17.0
