### ISSUE TITLE
Add existing 1.0.0 contracts

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-deployments#150]
### ChainId

1

### Chainlist

1

### Contract deployed

- [X] I confirm that the contracts are deployed
- [x] [Add ProxyFactory v1.0.0](https://github.com/safe-global/safe-deployments/pull/151)
- [x] [Add MultiSend v1.0.0](https://github.com/safe-global/safe-deployments/pull/152)

### Version of contracts deployed

v1.0.0

### Relevant information

Currently, we only have the GnosisSafe contract address for 1.0.0, and it blocks some projects that are looking to support a wide range of safe versions and rely on this repo to get contract addresses. We should add all 1.0.0 contracts

**Comment by germartinez** [comment]
@mikhailxyz
Not only for `chainId` = 1.
Also 4, 5, 42 and 100
