### ISSUE TITLE
Different proxy factory for Optimism Goerli

### ISSUE THREAD

**Issue by 0xslipk** [safe-global/safe-deployments#163]
Hello guys,

I am trying to predict the safe address with `create2` for a cross-chain Safe for goerli, mumbai, optimism-goerli, aurora-testnet, arbitrum-goerli, avalanche-fuji and binance-testnet. The problem is that I am using the proxy factory address as first parameter for  [getCreate2Address](https://github.com/ethers-io/ethers.js/blob/v5.7.2/packages/address/src.ts/index.ts#L143-L151), but `optimism-goerli` on [proxy_factory.json](https://github.com/safe-global/safe-deployments/blob/v1.17.0/src/assets/v1.3.0/proxy_factory.json#L40) has different address that  for example [goerli](https://github.com/safe-global/safe-deployments/blob/v1.17.0/src/assets/v1.3.0/proxy_factory.json#L10). is this an error or correct?.

I am asking, because I can found the [goerli address](https://goerli-optimism.etherscan.io/address/0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2#code) on optimism-goerli.

Thank you in advance.

**Comment by moisses89** [comment]
It is not an error, they used different deterministic deployment proxy ( [singleton-factory](https://github.com/safe-global/safe-singleton-factory) ) to create them. that's the reason for have two different addresses.

**Comment by moisses89** [comment]
@0xslipk related your question https://github.com/safe-global/safe-contracts/issues/460 
If no more concerns about this, the issue should be closed. :sweat_smile:

**Comment by Hsaameett57** [comment]
Access

**Comment by sunliang711** [comment]
If I want to use the same safe address on all networks, this can't be done, that's so bad ):

**Comment by 0xslipk** [comment]
> @0xslipk related your question https://github.com/safe-global/safe-contracts/issues/460 
> 
> If no more concerns about this, the issue should be closed. :sweat_smile: 

Awesome thank you 🙏

**Comment by 0xslipk** [comment]
> If I want to use the same safe address on all networks, this can't be done, that's so bad ): 

I actually did, so It can be done. 😬

**Comment by sunliang711** [comment]
> > If I want to use the same safe address on all networks, this can't be done, that's so bad ):
> 
> I actually did, so It can be done. 😬

How did you do that ?  I have used the safe sdk to predict safe address with same owners same  threshold and same salt, but the address of optimistic chain  is different with others (ethereum polygon bsc arbitrum are the same).
This is my code:
```
export async function deploySafe(rpc: string, privateKey: string, owners: Array<string>, threshold: number, nonce: string, dryRun: boolean,isL1SafeMasterCopy: boolean) {
    // check owners duplicate
    if (new Set(owners).size != owners.length) {
        throw new Error("duplicate owners")
    }

    if (threshold > owners.length) {
        throw new Error("threshold greater than owners count")
    }

    owners.forEach(owner => {
        checkAddress(owner, `owner: ${owner} is not an valid address`)
    })

    const ethAdapter = createAdapter(rpc, privateKey)
    const sender = await ethAdapter.getSigner()?.getAddress()
    console.log("deployer:", sender)
    const safeFactory = await SafeFactory.create({ ethAdapter,isL1SafeMasterCopy })

    const saltNonce = nonce.length > 0 ? nonce : Date.now().toString()
    console.log("nonce:", saltNonce)

    const safeDeploymentConfig: SafeDeploymentConfig = {
        saltNonce
    }

    const safeAccountConfig: SafeAccountConfig = {
        owners,
        threshold
    }

    // predict deployed address
    console.log("predict deploy address..")
    const predictedDeployAddress = await safeFactory.predictSafeAddress({
        safeAccountConfig,
        safeDeploymentConfig
    })
    console.log('Predicted deployed address:', predictedDeployAddress)
    if (dryRun) {
        return
    }

    function callback(txHash: string) {
        console.log('Transaction hash:', txHash)
    }

    console.log("deploy..")
    const safe: Safe = await safeFactory.deploySafe({
        safeAccountConfig,
        safeDeploymentConfig,
        callback
    })
    const newSafeAddress = safe.getAddress()

    console.log('Deployed Safe:', newSafeAddress)
}

```
