### ISSUE TITLE
[New chain]: Haqq network testnet

### ISSUE THREAD

**Issue by Hirama** [safe-global/safe-deployments#172]
### ChainId

54211

### Chainlist

https://chainlist.org/chain/54211

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

Explorer: https://explorer.testedge2.haqq.network/
Docs: https://docs.haqq.network/
https://islamiccoin.net/

**Comment by nvd67** [comment]
Is there any faucet which I can use to get some ISLM coins and do some transactions?

**Comment by Hirama** [comment]
> Is there any faucet which I can use to get some ISLM coins and do some transactions?

https://testedge2.haqq.network/
