### ISSUE TITLE
[New chain]: Thundercore Mainnet

### ISSUE THREAD

**Issue by nick8319** [safe-global/safe-deployments#188]
### ChainId

108

### Chainlist

https://chainlist.org/chain/108

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

RPC endpoint: https://mainnet-rpc.thundercore.com/
Block explorer: https://viewblock.io/thundercore

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-108.json

PR: #187

**Comment by Hsaameett57** [comment]
Access

**Comment by DevCon1100** [comment]
Access
