### ISSUE TITLE
[New chain]: Crossbell

### ISSUE THREAD

**Issue by iavl** [safe-global/safe-deployments#204]
### ChainId

3737

### Chainlist

https://chainlist.org/chain/3737

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

ChainID: 3737
RPC endpoint: https://rpc.crossbell.io
Block explorer: https://scan.crossbell.io/

PR: https://github.com/safe-global/safe-deployments/pull/205

**Comment by moisses89** [comment]
https://github.com/safe-global/safe-deployments/pull/205
