### ISSUE TITLE
[New chain]: Scroll Alpha

### ISSUE THREAD

**Issue by pajicf** [safe-global/safe-deployments#216]
### ChainId

534353

### Chainlist

https://chainlist.org/chain/534353

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

Added support for Scroll Alpha in this [PR](https://github.com/safe-global/safe-deployments/pull/212).

RPC: https://alpha-rpc.scroll.io/l2
Chainlist: https://chainlist.org/chain/534353

**Comment by OrestTa** [comment]
Can be closed
