### ISSUE TITLE
[New chain]: Ultron Testnet

### ISSUE THREAD

**Issue by softwareultron** [safe-global/safe-deployments#265]
### ChainId

1230

### Chainlist

https://chainlist.org/chain/1230

### Contract deployed

- [x] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

Block explorer: https://explorer.ultron-dev.io/
RPC: https://ultron-dev.io

**Comment by moisses89** [comment]
@softwareultron are you going to create a PR to add this addressess to this project?

**Comment by softwareultron** [comment]
@moisses89 Added!
https://github.com/safe-global/safe-deployments/pull/271 
Could you please check it?
