### ISSUE TITLE
Publish an updated version to NPM

### ISSUE THREAD

**Issue by softwareultron** [safe-global/safe-deployments#279]
Could you please publish the new version to NPM? 
The Ultron network does not exist in the current version (1230, 1231), so we can not use this package for the moment.
PR: https://github.com/safe-global/safe-deployments/pull/274
Thank you!

https://www.npmjs.com/package/@safe-global/safe-deployments
<img width="387" alt="image" src="https://github.com/safe-global/safe-deployments/assets/99988878/0783b4d2-b67f-4135-a655-a681e5724e9c">

**Comment by softwareultron** [comment]
@mmv08 @Uxio0 ?

**Comment by mmv08** [comment]
Have just pushed an updated version, apologies for the delay
