### ISSUE TITLE
[New chain]: Scroll Sepolia Testnet

### ISSUE THREAD

**Issue by nick8319** [safe-global/safe-deployments#284]
### ChainId

534351

### Chainlist

https://chainlist.org/chain/534351

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

RPC endpoint: https://sepolia-rpc.scroll.io/
Block explorer: https://sepolia-blockscout.scroll.io/

https://github.com/safe-global/safe-deployments/pull/283

**Comment by moisses89** [comment]
PR closed #283
