### ISSUE TITLE
Publish an updated version to NPM

### ISSUE THREAD

**Issue by gnarco** [safe-global/safe-deployments#306]
Could you please publish the new version to NPM?
The Polygon Supernet Arianee does not exist in the current version, so we can not use this package for the moment.

Thank you!

PS : based on release lifecycle, it should be done every month :)

**Comment by gnarco** [comment]
@mmv08 @Uxio0 ?

**Comment by mmv08** [comment]
Have just published 1.28.0 to npm. Sorry for the delay.

**Comment by gnarco** [comment]
Thanks yoy very much !!
