### ISSUE TITLE
How to use a safe on our chain ? 

### ISSUE THREAD

**Issue by gnarco** [safe-global/safe-deployments#330]
We want to follow the procedure described it here : https://github.com/safe-global/safe-infrastructure

So we started adding our token to safe-deployment repo and request a bump in the NPM package. Done.

But, other libraries / tools still refer to old versions that does not include the newest safe-deployment package.

So, it seems that the whole stack needs to be bumped

is it right ? or do we miss something ?

Thanks !

**Comment by mmv08** [comment]
Yes, you're correct. Unfortunately, that's out of scope for the repository. Creating an issue directly in the safe-infrastructure repo or the corresponding tools' repos is better.
