### ISSUE TITLE
There is no chain_id= 97 for 1.4.1 contracts

### ISSUE THREAD

**Issue by IvanKodak** [safe-global/safe-deployments#331]
I want to test gnosis multisig creation on BSC testnet, but I can't do it, because there is no BSC testnet chain id for 1.4.1 version. 
Please check: https://github.com/safe-global/safe-deployments/blob/v1.28.0/src/assets/v1.4.1/safe_proxy_factory.json

But in network contract is exist: https://testnet.bscscan.com/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

**Comment by mmv08** [comment]
> I want to test gnosis multisig creation on BSC testnet, but I can't do it, because there is no BSC testnet chain id for 1.4.1 version. Please check: https://github.com/safe-global/safe-deployments/blob/v1.28.0/src/assets/v1.4.1/safe_proxy_factory.json
> 
> But in network contract is exist: https://testnet.bscscan.com/address/0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67

Since the deployment process is trustless (anyone can deploy contracts), such things may happen. You create a PR to add the address to the list of deployments

**Comment by DmytroShalaiev** [comment]
@mmv08 the PR is waiting for review, thanks.

**Comment by nlordell** [comment]
Closed by #372
