### ISSUE TITLE
[New chain]: Optimism Sepolia

### ISSUE THREAD

**Issue by dcbuild3r** [safe-global/safe-deployments#367]
### ChainId

11155420

### Chainlist

https://chainlist.org/chain/11155420

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.4.1

### Relevant information

https://sepolia-optimism.etherscan.io/

Couldn't verify the contracts below, because the `hardhat etherscan-verify` integration is broken in the `safe-smart-account` repo. Using the custom API url for Optimism Sepolia etherscan did not work. The deployment files for each file can be found below (compiled on branch `v1.4.1`):

[CompatibilityFallbackHandler.json](https://github.com/safe-global/safe-deployments/files/14043512/CompatibilityFallbackHandler.json)
[CreateCall.json](https://github.com/safe-global/safe-deployments/files/14043513/CreateCall.json)
[MultiSend.json](https://github.com/safe-global/safe-deployments/files/14043514/MultiSend.json)
[MultiSendCallOnly.json](https://github.com/safe-global/safe-deployments/files/14043515/MultiSendCallOnly.json)
[Safe.json](https://github.com/safe-global/safe-deployments/files/14043516/Safe.json)
[SafeL2.json](https://github.com/safe-global/safe-deployments/files/14043517/SafeL2.json)
[SafeProxyFactory.json](https://github.com/safe-global/safe-deployments/files/14043518/SafeProxyFactory.json)
[SignMessageLib.json](https://github.com/safe-global/safe-deployments/files/14043519/SignMessageLib.json)
[SimulateTxAccessor.json](https://github.com/safe-global/safe-deployments/files/14043520/SimulateTxAccessor.json)
[TokenCallbackHandler.json](https://github.com/safe-global/safe-deployments/files/14043521/TokenCallbackHandler.json)

**Comment by dcbuild3r** [comment]
I also had to patch the `safe-singleton-factory` (to use v 1.0.18) dependency of `safe-smart-account` in order to use one that already had an OP Sepolia deployment.

**Comment by emilianobonassi** [comment]
supporting this!

**Comment by nlordell** [comment]
Deployments have been added.
