### ISSUE TITLE
[New chain]: Amoy Testnet

### ISSUE THREAD

**Issue by Diego-c22** [safe-global/safe-deployments#435]
### ChainId

80002

### Chainlist

https://chainlist.org/chain/80002

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

Blockexplorer: https://www.oklink.com/amoy
PR has already been created

**Comment by garthbrydon** [comment]
Hi @Diego-c22 thanks for getting v1.3.0 deployed; any idea if/when 1.4.1 contracts will be deployed?
