### ISSUE TITLE
no official deployments for `SafeToL2Migration.sol`

### ISSUE THREAD

**Issue by gosuto-inzasheru** [safe-global/safe-deployments#444]
i found it at `0x1Ba30910CE8Eb45b276aa7c89C38FC52228B85CB` on polygon and optimism after bumping into this comment: https://github.com/safe-global/safe-smart-account/pull/685#issuecomment-1786969800. it also seems to exist on arb1 but not verified. the address is empty on base 

im not really sure if that is an "official" deployment though, given i cannot find that address in this repo (or any other mention of `SafeToL2Migration.sol`)

**Comment by gosuto-inzasheru** [comment]
@Uxio0 tagging you if you dont mind, since it is your comment that got me to the `0x1ba3` address :)

**Comment by mmv08** [comment]
The contract hasn't been audited yet that's why it's not a part of the deployment

**Comment by remedcu** [comment]
The official one is deployed here: https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.4.1/safe_to_l2_migration.json
