### ISSUE TITLE
Fully Automate New Chain Checks

### ISSUE THREAD

**Issue by nlordell** [safe-global/safe-deployments#661]
Currently, there is a manual step of running new chain checks (`bash bin/github-review.sh`) for new issues. This can be automated and run in CI to reduce the manual checks needed by the protocol team when merging new chains.

The expected outcome is a new GitHub action that runs on new chain PRs and checks that implements all the checks from the GitHub review script. In addition, some further automation is required:
- We could fetch the version, chain id and rpc from the PR.
- If there are changes in any other path other than src/assets, the script should show an error
- We should ensure there are not more than a single chain ID being added in a PR

**Comment by remedcu** [comment]
Fixed in #683
