### ISSUE TITLE
RPC independence based on chainlist RPC list for review

### ISSUE THREAD

**Issue by remedcu** [safe-global/safe-deployments#688]
Currently, the chain ID and the RPC link are provided by the person who creates the PR with the contracts being added.

As an added security, we could retrieve the RPC list from the `ethereum-lists/chains` repo and use that in the script.

## Expected Outcome

- Retrieve the RPC list from the `ethereum-lists/chains` repo: https://github.com/ethereum-lists/chains/tree/master/_data/chains (thanks @mmv08)

## Alternatives

- Retrieve the RPC list from the ChainList GitHub repo: https://github.com/DefiLlama/chainlist/blob/main/constants/extraRpcs.js#L166
- Do nothing

**Comment by mmv08** [comment]
> Possible Issue: If we parse based on the website structure, then changes in the website might break the script.

Why do you need the website? They website uses the JSON files hosted on github: https://github.com/ethereum-lists/chains/tree/master/_data/chains

**Comment by mmv08** [comment]
> Yes, we could use the official Chainlist repo as well, which is mentioned in the Alternatives section of the issue.

The repo in the alternatives is the defillama chainlist, but we follow the one I linked

**Comment by remedcu** [comment]
But we did require that the chain should be listed on https://chainlist.org/ right? Or am I mistaken?

**Comment by mmv08** [comment]
> But we did require that the chain should be listed on https://chainlist.org/ right? Or am I mistaken?

It uses the chainlist from the ethereum-lists repo: https://github.com/DefiLlama/chainlist/blob/main/utils/fetch.js#L99

**Comment by remedcu** [comment]
TIL about it! Thanks! Updated the initial description.

**Comment by remedcu** [comment]
Closed with #873
