### ISSUE TITLE
Please add Arbitrum Sepolia chainId to assets list

### ISSUE THREAD

**Issue by IvanKodak** [safe-global/safe-deployments#720]
Please add chainId= 421614 to the assets list

**Comment by IvanKodak** [comment]
@bertux @develCuy @liliya-soroka @katspaugh please check

**Comment by mmv08** [comment]
Hey @IvanKodak , you can deploy it by following the instructions in https://github.com/safe-global/safe-smart-account

The team is currently not deploying contracts to other networks as the demand is magnitudes larger than the capacity.

**Comment by IvanKodak** [comment]
@mmv08 contract already deployed, the issue is about adding arbitrum sepolia chainId to assets list

**Comment by mmv08** [comment]
> @mmv08 contract already deployed, the issue is about adding arbitrum sepolia chainId to assets list

you can create a pr in this case
