### ISSUE TITLE
[New Chain] Game7 Mainnet

### ISSUE THREAD

**Issue by msvstj** [safe-global/safe-deployments#844]
### ChainId
2187 

### Chainlist
https://chainlist.org/chain/2187 

 ### Contract deployed
* [x]  I confirm that the contracts are deployed
 
### Version of contracts deployed
 v1.4.1
 
Related: 
https://github.com/safe-global/safe-deployments/pull/843
https://github.com/safe-global/safe-eth-py/issues/1397

**Comment by remedcu** [comment]
#843 merged
